### ISSUE TITLE
启动没报错，但是没执行任何步骤

### ISSUE THREAD

**Issue by luoxi001713** [macacajs/NoSmoke#34]
我使用的默认的配置，chrome和web-pc,  启动没有报错。
但是网站打开后一直不动，报告页面只是时间变化，其他没变化，是哪里没配对么？

**Comment by SamuelZhaoY** [comment]
用 electron + web-pc

**Comment by luoxi001713** [comment]
我配置文件如下，执行npm run dev后，electron窗口打开了，macaca的网站，但是没任何动作，是哪里不对么？
```
# 1. Initialization option
desiredCapabilities:
#  Web Configuration
  platformName: 'Desktop'
  browserName: 'Electron'
  url: 'https://macacajs.github.io'

# 2. Crawling option
crawlingConfig:

# Web Configuration
  platform: 'pc-web'
  clickTypes:
    - 'a'
  editTypes:
    - 'input'
...
```
